CREATE TABLE M1 (
	K INT PRIMARY KEY,
	V VARCHAR(20)
);

CREATE TABLE S1 (
	K INT PRIMARY KEY,
	MFK INT FOREIGN KEY REFERENCES M1(K),
	V VARCHAR(20)
);

CREATE TABLE M2 (
	K1 INT,
	K2 INT,
	V VARCHAR(20),
	PRIMARY KEY (K1, K2)
);

CREATE TABLE S2 (
	K INT PRIMARY KEY,
	MFK1 INT,
	MFK2 INT,
	V VARCHAR(20),
	FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
);

INSERT INTO M1 (K, V) VALUES (1, 'Parent1'), (2, 'Parent2'), (3, 'Parent3');
INSERT INTO S1 (K, MFK, V) VALUES (1, 1, 'Child1'), (2, 2, 'Child2'), (3, 3, 'Child3');
INSERT INTO M2 (K1, K2, V) VALUES (1, 10, 'ParentA'), (2, 20, 'ParentB'), (3, 30, 'ParentC');
INSERT INTO S2 (K, MFK1, MFK2, V) VALUES (1, 1, 10, 'ChildA'), (2, 2, 20, 'ChildB'), (3, 3, 30, 'ChildC');