WITH tmp1 as (SELECT C_NAME, N_NAME, SUM(O_TOTALPRICE) AS SUMA
					FROM CUSTOMER
					JOIN ORDERS ON O_CUSTKEY = C_CUSTKEY
					JOIN NATION ON C_NATIONKEY = N_NATIONKEY
					WHERE EXTRACT(YEAR FROM O_ORDERDATE) = 1997
					GROUP BY C_NAME, N_NAME),
 	tmp2 as (SELECT N_NAME as kraj, MAX(SUMA) as maxV
			 	FROM tmp1
			 	GROUP BY N_NAME),
	tmp3 as (SELECT N_NAME as N_NAME2, C_NAME, SUMA
				FROM tmp2
				JOIN tmp1 ON N_NAME = kraj 
							AND maxV = SUMA)


SELECT N_NAME, C_NAME, SUMA
	FROM NATION
	LEFT JOIN tmp3 on N_NAME = N_NAME2;