WITH tmp as (SELECT P_NAME, SUM(PS_AVAILQTY) as SUMA
				FROM PART
				JOIN PARTSUPP ON PS_PARTKEY = P_PARTKEY
				JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY
				JOIN NATION ON N_NATIONKEY = S_NATIONKEY
				JOIN REGION ON R_REGIONKEY = N_REGIONKEY
				WHERE P_CONTAINER = 'JUMBO PKG' 
					AND R_NAME = 'MIDDLE EAST'
				GROUP BY P_NAME),
	tmp2 as (SELECT P_NAME
				FROM PART
				WHERE P_CONTAINER = 'JUMBO PKG')
				
SELECT P_NAME, COALESCE(SUMA, 0)
	FROM tmp2
	LEFT JOIN tmp USING (P_NAME);
				