DECLARE @table TABLE (id INT);

CREATE TABLE #local (id INT);

CREATE TABLE ##global (id INT);

INSERT INTO @table VALUES (1);
INSERT INTO #local VALUES (1);
INSERT INTO ##global VALUES (1);

SELECT * FROM tempdb.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '#%';
