INSERT INTO BankAccount (Balance) VALUES (3000), (4000), (5000);

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;
	SELECT * FROM BankAccount;
	EXEC sp_lock;
COMMIT;

BEGIN TRANSACTION;
	SELECT * FROM BankAccount WITH (NOLOCK);
	EXEC sp_lock;
COMMIT;